---
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: base-cmake-centos7
    image: centos:7
    privileged: true
  - name: base-cmake-ubuntu
    image: ubuntu:xenial
    privileged: true
  - name: base-cmake-debian
    image: debian:buster
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
